services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: aula1
    container_name: aula1-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - aula1-network
    
  nginx:
    image: nginx:stable-alpine3.17
    container_name: aula1-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - aula1-network

networks:
  aula1-network:
    driver: bridge