services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: coti-laravel
    container_name: coti-laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - coti-laravel-network
    
  nginx:
    image: nginx:stable-alpine3.17
    container_name: coti-laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - coti-laravel-network

  db:
    image: mysql:8.3.0
    container_name: coti-laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - coti-laravel-network

networks:
  coti-laravel-network:
    driver: bridge